server: Use zeroed() to initialize libc::msghdr struct
Without this change, compiling with muslc will throw:
```
  error: cannot construct `msghdr` with struct literal syntax due to private fields
  = note: ...and other private fields `__pad1` and `__pad2` that were not provided

  error[E0063]: missing field `__pad1` in initializer of `cmsghdr`
```

Musl's structs have private padding fields (__pad1, __pad2) that
cannot be initialized with struct literals.

So zeroed() the struct and initialize elements manually.
This approach works with both glibc and muslc.