ci: disable failing aarch64 musl builds
These builds are failing to compile with following error:
```
error: Cannot build '/nix/store/2l7xv5py9s53dxivdh9c819jjq6qkxvm-lightway-client-aarch64-unknown-linux-musl.drv'.
       Reason: builder failed with exit code 101.
       Output paths:
         /nix/store/h5nzw5q7hsxi28d49s5331332n3hz2r6-lightway-client-aarch64-unknown-linux-musl
       Last 25 log lines:
       >   autoreconf: configure.ac: not using Gettext
       >   autoreconf: running: aclocal --force -I m4
       >   autoreconf: configure.ac: tracing
       >   autoreconf: configure.ac: creating directory build-aux
       >   autoreconf: running: libtoolize --copy --force
       >   autoreconf: configure.ac: not using Intltool
       >   autoreconf: configure.ac: not using Gtkdoc
       >   autoreconf: running: aclocal --force -I m4
       >   autoreconf: running: /nix/store/ansdrmva5pl4xhav2hgq7430pkls8512-autoconf-2.72/bin/autoconf --force
       >   autoreconf: running: /nix/store/ansdrmva5pl4xhav2hgq7430pkls8512-autoconf-2.72/bin/autoheader --force
       >   autoreconf: running: automake --add-missing --copy --force-missing
       >   configure.ac:25: installing 'build-aux/compile'
       >   configure.ac:27: installing 'build-aux/config.guess'
       >   configure.ac:27: installing 'build-aux/config.sub'
       >   configure.ac:31: installing 'build-aux/install-sh'
       >   configure.ac:31: installing 'build-aux/missing'
       >   Makefile.am: installing 'build-aux/depcomp'
       >   parallel-tests: installing 'build-aux/test-driver'
       >   autoreconf: Leaving directory '.'
       >   make: warning: -j4 forced in submake: resetting jobserver mode.
       >   make[1]: warning: -j5 forced in submake: resetting jobserver mode.
       >   make[2]: warning: -j5 forced in submake: resetting jobserver mode.
       >   make[3]: warning: -j5 forced in submake: resetting jobserver mode.
       >   *** stack smashing detected ***: terminated
       > warning: build failed, waiting for other jobs to finish...
```

Since compiling from aarch64 linux machine using musl c is not
a common workflow, comment it out for now and fix later